controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout
  methods: GET
index:
  path: /
  controller: App\Controller\SearchController::search
update_saved_films:
  path: /update-saved-films
  methods: [POST]
  defaults:
    _controller: App\Controller\ApiResponseController::updateSavedFilms
get_saved_films:
  path: /get-saved-films
  methods: [GET]
  defaults:
    _controller: App\Controller\ApiResponseController::getSavedFilms
remove_film:
  path: /remove-film
  methods: [GET|POST]
  defaults:
    _controller: App\Controller\AccountController::removeFilm
